### ISSUE TITLE
Discord invite in Readme is invalid

### ISSUE THREAD

**Issue by Eph00n** [ankurv2k6/daksh-toolchanger-v2#10]
I would like to follow along in Discord, however the invite links in the ReadMe and issue #8 are invalid.
Could you kindly create a new one?
(The expiration time for invite links is set to 7 days as standard and can be changed when creating the invite.)

**Comment by 3dfiyMyLife** [comment]
https://discord.gg/wJqUzYxYXH

Try this. Have changed the invite settings

**Comment by Eph00n** [comment]
That worked, thank you very much!
