### ISSUE TITLE
The Discord invite in the README is invalid

### ISSUE THREAD

**Issue by bmurphy1976** [ankurv2k6/daksh-toolchanger-v2#8]
I'm interested in following along with this project and perhaps contributing down the road however I noticed the Discord link in the README is invalid/expired.

<img width="526" alt="image" src="https://github.com/ankurv2k6/daksh-toolchanger-v2/assets/270488/2d6e9e7e-0408-4d45-9554-0ef45152bd6c">

**Comment by 3dfiyMyLife** [comment]
Hi, you can try this https://discord.gg/DzFQBuGg

**Comment by bmurphy1976** [comment]
@3dfiyMyLife that worked, thanks!
